# Generated by Django 4.2.2 on 2023-06-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
